name: Build and deploy

on:
    push:
        branches: [main]

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: Prepare environment
              uses: actions/setup-node@v2
              with:
                node-version: "16"

            - name: Install Prerequisites
              run: npm install --global sperm pnpm

            - name: Install Dependencies
              run: pnpm i
              
            - name: Build Plugin
              run: |
                  mkdir .dist
                  sperm build --outdir "../../.dist/"
              
            - name: Copy README.md
              run: |
                  cp README.md .dist/README.md

            - name: Deploy to GitHub Pages
              uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: ./.dist
                  # Makes it so the md files in the previous step get processed by GitHub Pages
                  enable_jekyll: true